/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snackbooth.GUI;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import snackbooth.Account.Admin;
import snackbooth.Account.Customer;
import snackbooth.Database.AccountManagement;
import snackbooth.Database.DrinkManagement;
import snackbooth.Database.FoodManagement;
import snackbooth.Database.OrderManagement;
import snackbooth.Drink.ChocolateSprinkles;
import snackbooth.Drink.Drink;
import snackbooth.Drink.DrinkFactory;
import snackbooth.Drink.Ice;
import snackbooth.Drink.Milk;
import snackbooth.Drink.Sugar;
import snackbooth.Food.BBQSauce;
import snackbooth.Food.Cheese;
import snackbooth.Food.ChiliSauce;
import snackbooth.Food.Food;
import snackbooth.Food.Lettuce;
import snackbooth.Food.FoodFactory;
import snackbooth.Food.Ketchup;
import snackbooth.Food.Mustard;
import snackbooth.Food.Onions;
import snackbooth.Kiosk;
import snackbooth.SnackBooth;

/**
 *
 * @author PC
 */
public class KioskGUI extends javax.swing.JFrame {

    /**
     * Creates new form Kiosk
     */
    int product;
    Kiosk kiosk;
    String size;
    String toasted = "";
    String totalCost;
    double cost;
    double newBalance;
    String drinkItemOri;
    String drinkItem;
    String foodItemOri;
    String foodItem;
    String order;
    String account;
    Drink drinkOrder;
    Drink drinkOrderBackup;
    Food foodOrder;
    Food foodOrderBackup;

    DrinkFactory df = DrinkFactory.getInstance();
    FoodFactory ff = FoodFactory.getInstance();
    OrderManagement orderMgmt;
    AccountManagement accMgmt = new AccountManagement();
    FoodManagement foodMgmt = FoodManagement.getInstance();
    DrinkManagement drinkMgmt = DrinkManagement.getInstance();

    public KioskGUI() {
        initComponents();

        populateCards();
        populateFood();
    }

    // Populates the cmbCards with account IDs from account.txt
    private void populateCards() {

        List<String> accounts;
        accounts = accMgmt.getEntries();
        cmbCards.removeAllItems();

        for (int i = 0; i < accounts.size(); i++) {
            cmbCards.addItem(accounts.get(i));
        }
    }

    // Populates the cmbFood with food items from food.txt
    private void populateFood() {

        List<String> food;
        food = foodMgmt.getNames();
        cmbFood.removeAllItems();
        cmbFood.addItem("--select--");

        for (int i = 0; i < food.size(); i++) {
            cmbFood.addItem(food.get(i));
        }
    }

    public void bindKiosks(Kiosk myK) {

        kiosk = myK;
        orderMgmt = new OrderManagement(this.kiosk);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        cmbCards = new javax.swing.JComboBox<>();
        btnScan = new javax.swing.JButton();
        pnlMainMenu = new javax.swing.JPanel();
        btnDrinks = new javax.swing.JButton();
        btnFood = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        lblBalanceMain = new javax.swing.JLabel();
        pnlDrinks = new javax.swing.JPanel();
        lblDrinks = new javax.swing.JLabel();
        lblDrinks2 = new javax.swing.JLabel();
        lblDrinks1 = new javax.swing.JLabel();
        cmbMilk = new javax.swing.JComboBox<>();
        lblAddOn = new javax.swing.JLabel();
        cmbSugar = new javax.swing.JComboBox<>();
        lblAddOn1 = new javax.swing.JLabel();
        cmbIce = new javax.swing.JComboBox<>();
        lblAddOn2 = new javax.swing.JLabel();
        cmbChoc = new javax.swing.JComboBox<>();
        lblAddOn3 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblNext = new javax.swing.JLabel();
        scrlDrinks = new javax.swing.JScrollPane();
        txtpDrinks = new javax.swing.JTextPane();
        btnTea = new javax.swing.JButton();
        btnMilo = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        btnSmall = new javax.swing.JButton();
        btnLarge = new javax.swing.JButton();
        btnMedium = new javax.swing.JButton();
        btnAddOn = new javax.swing.JButton();
        pnlFood = new javax.swing.JPanel();
        lblFood = new javax.swing.JLabel();
        cmbFood = new javax.swing.JComboBox<>();
        scrlFood = new javax.swing.JScrollPane();
        txtpFood = new javax.swing.JTextPane();
        lblFood2 = new javax.swing.JLabel();
        lblIngredients = new javax.swing.JLabel();
        lblSauces = new javax.swing.JLabel();
        chkBBQ = new javax.swing.JCheckBox();
        chkChili = new javax.swing.JCheckBox();
        chkKetchup = new javax.swing.JCheckBox();
        chkMustard = new javax.swing.JCheckBox();
        chkLettuce = new javax.swing.JCheckBox();
        chkOnions = new javax.swing.JCheckBox();
        chkCheese = new javax.swing.JCheckBox();
        btnSelect = new javax.swing.JButton();
        lblAvailability = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpSelected = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpCost = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpAvailability = new javax.swing.JTextPane();
        btnAddIngredients = new javax.swing.JButton();
        lblNext1 = new javax.swing.JLabel();
        btnNext1 = new javax.swing.JButton();
        tbtnToastBread = new javax.swing.JToggleButton();
        pnlPayment = new javax.swing.JPanel();
        lblTotalPrice = new javax.swing.JLabel();
        scrlPrice = new javax.swing.JScrollPane();
        txtpTotal = new javax.swing.JTextArea();
        lblPayment = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        lblBalanceAfter = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        lblTransactionLog = new javax.swing.JLabel();
        lblDone = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snack Kiosk");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setText("Snack Kiosk");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Roboto Th", 1, 18)); // NOI18N
        lblUser.setText("user");
        lblUser.setVisible(false);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(12, 12, 12)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel)
                            .addComponent(lblUser))
                        .addContainerGap())))
        );

        pnlMain.setLayout(new java.awt.CardLayout());

        pnlLogin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pnlLoginComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlLoginComponentShown(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Roboto Lt", 0, 36)); // NOI18N
        lblLogin.setText("<html>Please place your ID Card<br>on the reader to begin.</html>");
        lblLogin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblLoginComponentShown(evt);
            }
        });

        cmbCards.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TP034526" }));

        btnScan.setText("Scan");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCards, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)))
                .addGap(196, 196, 196))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(cmbCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnScan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pnlMain.add(pnlLogin, "pnlLogin");

        btnDrinks.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnDrinks.setText("Drinks");
        btnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinksActionPerformed(evt);
            }
        });

        btnFood.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnFood.setText("Food");
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });

        lblCategory.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblCategory.setText("Choose a category:");
        lblCategory.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblCategoryComponentShown(evt);
            }
        });

        lblBalanceMain.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        lblBalanceMain.setText("Balance: ");
        lblBalanceMain.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBalanceMainComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pnlMainMenuLayout = new javax.swing.GroupLayout(pnlMainMenu);
        pnlMainMenu.setLayout(pnlMainMenuLayout);
        pnlMainMenuLayout.setHorizontalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalanceMain)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainMenuLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(btnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFood, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        pnlMainMenuLayout.setVerticalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBalanceMain)
                .addGap(18, 18, 18)
                .addComponent(lblCategory)
                .addGap(91, 91, 91)
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFood, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pnlMain.add(pnlMainMenu, "pnlMainMenu");

        lblDrinks.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblDrinks.setText("1. Pick your drink.");
        lblDrinks.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblDrinksComponentShown(evt);
            }
        });

        lblDrinks2.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblDrinks2.setText("3. Choose add-ons.");
        lblDrinks2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblDrinks2ComponentShown(evt);
            }
        });

        lblDrinks1.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblDrinks1.setText("2. Select a drink size.");
        lblDrinks1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblDrinks1ComponentShown(evt);
            }
        });

        cmbMilk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Some", "More" }));
        cmbMilk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMilkItemStateChanged(evt);
            }
        });
        cmbMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMilkActionPerformed(evt);
            }
        });

        lblAddOn.setText("Milk");

        cmbSugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Some", "More" }));

        lblAddOn1.setText("Sugar");

        cmbIce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Some", "More" }));

        lblAddOn2.setText("Ice");

        cmbChoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Some", "More" }));

        lblAddOn3.setText("Chocolate Sprinkles");

        btnNext.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblNext.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNext.setText("Select \"Next\" to continue >>>");

        txtpDrinks.setEditable(false);
        scrlDrinks.setViewportView(txtpDrinks);

        btnTea.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnTea.setText("Tea");
        btnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeaActionPerformed(evt);
            }
        });

        btnMilo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMilo.setText("Milo");
        btnMilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiloActionPerformed(evt);
            }
        });

        btnCoffee.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCoffee.setText("Coffee");
        btnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffeeActionPerformed(evt);
            }
        });

        btnSmall.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnSmall.setText("S");
        btnSmall.setEnabled(false);
        btnSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmallActionPerformed(evt);
            }
        });

        btnLarge.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnLarge.setText("L");
        btnLarge.setEnabled(false);
        btnLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLargeActionPerformed(evt);
            }
        });

        btnMedium.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnMedium.setText("M");
        btnMedium.setEnabled(false);
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        btnAddOn.setText("Add");
        btnAddOn.setEnabled(false);
        btnAddOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDrinksLayout = new javax.swing.GroupLayout(pnlDrinks);
        pnlDrinks.setLayout(pnlDrinksLayout);
        pnlDrinksLayout.setHorizontalGroup(
            pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinksLayout.createSequentialGroup()
                .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDrinksLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDrinksLayout.createSequentialGroup()
                                .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblDrinks2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAddOn2)
                                            .addComponent(cmbIce, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAddOn))
                                        .addGap(53, 53, 53)
                                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAddOn1)
                                            .addComponent(cmbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAddOn3)
                                            .addComponent(cmbChoc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(btnMilo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCoffee))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblDrinks1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(btnAddOn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(scrlDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDrinksLayout.setVerticalGroup(
            pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinksLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDrinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMilo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTea, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblDrinks1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDrinks2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAddOn1)
                            .addComponent(lblAddOn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDrinksLayout.createSequentialGroup()
                                .addComponent(cmbMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addComponent(lblAddOn2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbIce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDrinksLayout.createSequentialGroup()
                                        .addComponent(lblAddOn3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbChoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cmbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddOn))
                    .addComponent(scrlDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(pnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNext))
                .addGap(18, 18, 18))
        );

        pnlMain.add(pnlDrinks, "pnlDrinks");

        lblFood.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblFood.setText("1. Pick your food.");
        lblFood.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblFoodComponentShown(evt);
            }
        });

        cmbFood.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFoodItemStateChanged(evt);
            }
        });
        cmbFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFoodActionPerformed(evt);
            }
        });

        txtpFood.setEditable(false);
        scrlFood.setViewportView(txtpFood);

        lblFood2.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblFood2.setText("<html>2. Sandwich customisation<br> <h4>(If Sandwich selected)</h4></html>");
        lblFood2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblFood2ComponentShown(evt);
            }
        });

        lblIngredients.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        lblIngredients.setText("Ingredients");
        lblIngredients.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblIngredientsComponentShown(evt);
            }
        });

        lblSauces.setFont(new java.awt.Font("Roboto Lt", 1, 14)); // NOI18N
        lblSauces.setText("Sauces");
        lblSauces.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblSaucesComponentShown(evt);
            }
        });

        chkBBQ.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkBBQ.setText("BBQ");
        chkBBQ.setEnabled(false);

        chkChili.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkChili.setText("Chili");
        chkChili.setEnabled(false);

        chkKetchup.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkKetchup.setText("Ketchup");
        chkKetchup.setEnabled(false);

        chkMustard.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkMustard.setText("Mustard");
        chkMustard.setEnabled(false);

        chkLettuce.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkLettuce.setText("Lettuce");
        chkLettuce.setEnabled(false);

        chkOnions.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkOnions.setText("Onions");
        chkOnions.setEnabled(false);
        chkOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOnionsActionPerformed(evt);
            }
        });

        chkCheese.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        chkCheese.setText("Cheese");
        chkCheese.setEnabled(false);

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability: ");

        lblPrice.setText("Cost (RM): ");

        txtpSelected.setEditable(false);
        jScrollPane1.setViewportView(txtpSelected);

        txtpCost.setEditable(false);
        jScrollPane2.setViewportView(txtpCost);

        txtpAvailability.setEditable(false);
        jScrollPane3.setViewportView(txtpAvailability);

        btnAddIngredients.setText("Add Ingredients");
        btnAddIngredients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIngredientsActionPerformed(evt);
            }
        });

        lblNext1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNext1.setText("Select \"Next\" to continue >>>");

        btnNext1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNext1.setText("Next");
        btnNext1.setEnabled(false);
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        tbtnToastBread.setText("Toast Bread");
        tbtnToastBread.setEnabled(false);
        tbtnToastBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnToastBreadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFoodLayout = new javax.swing.GroupLayout(pnlFood);
        pnlFood.setLayout(pnlFoodLayout);
        pnlFoodLayout.setHorizontalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodLayout.createSequentialGroup()
                .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFoodLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFoodLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblNext1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFoodLayout.createSequentialGroup()
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFoodLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbFood, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlFoodLayout.createSequentialGroup()
                                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAvailability)
                                            .addComponent(lblPrice))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlFoodLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnAddIngredients))
                            .addGroup(pnlFoodLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblFood2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlFoodLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(tbtnToastBread, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFoodLayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIngredients)
                                        .addComponent(chkLettuce)
                                        .addComponent(chkCheese)
                                        .addComponent(chkOnions))
                                    .addGap(56, 56, 56)
                                    .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSauces)
                                        .addComponent(chkBBQ)
                                        .addComponent(chkChili)
                                        .addComponent(chkKetchup)
                                        .addComponent(chkMustard)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(scrlFood, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFoodLayout.setVerticalGroup(
            pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFoodLayout.createSequentialGroup()
                .addComponent(lblFood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFoodLayout.createSequentialGroup()
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSelect)
                                .addComponent(lblAvailability))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(lblFood2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbtnToastBread, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIngredients)
                            .addComponent(lblSauces))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBBQ)
                            .addComponent(chkLettuce))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkChili)
                            .addComponent(chkOnions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkKetchup)
                            .addComponent(chkCheese))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMustard)
                        .addGap(13, 13, 13)
                        .addComponent(btnAddIngredients))
                    .addComponent(scrlFood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNext1))
                .addContainerGap())
        );

        pnlMain.add(pnlFood, "pnlFood");

        lblTotalPrice.setFont(new java.awt.Font("Roboto Lt", 0, 36)); // NOI18N
        lblTotalPrice.setText("Total Cost: ");
        lblTotalPrice.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblTotalPriceComponentShown(evt);
            }
        });

        txtpTotal.setColumns(20);
        txtpTotal.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        txtpTotal.setRows(5);
        scrlPrice.setViewportView(txtpTotal);

        lblPayment.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblPayment.setText("The following amount will be deducted from your balance:");
        lblPayment.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblPaymentComponentShown(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblBalance.setText("Balance: ");
        lblBalance.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBalanceComponentShown(evt);
            }
        });

        lblBalanceAfter.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblBalanceAfter.setText("Balance After: ");
        lblBalanceAfter.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblBalanceAfterComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPaymentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblBalance)
                        .addComponent(lblTotalPrice)
                        .addComponent(lblBalanceAfter)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(scrlPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalanceAfter)
                .addGap(64, 64, 64)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMain.add(pnlPayment, "pnlPayment");

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblTransactions);

        lblTransactionLog.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        lblTransactionLog.setText("Transaction Log: ");
        lblTransactionLog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lblTransactionLogComponentShown(evt);
            }
        });

        lblDone.setText("Done");
        lblDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDoneActionPerformed(evt);
            }
        });

        btnView.setText("View More");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addComponent(lblTransactionLog, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 325, Short.MAX_VALUE))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransactionLog)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnView)
                .addGap(32, 32, 32)
                .addComponent(lblDone)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pnlMain.add(pnlAdmin, "pnlAdmin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void switchPanel(String pname) {

        CardLayout card = (CardLayout) pnlMain.getLayout();
        card.show(pnlMain, pname);

    }

    private void pnlLoginComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlLoginComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlLoginComponentHidden

    private void lblLoginComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblLoginComponentShown

    }//GEN-LAST:event_lblLoginComponentShown

    private void pnlLoginComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlLoginComponentShown

    }//GEN-LAST:event_pnlLoginComponentShown

    private void lblCategoryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCategoryComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCategoryComponentShown

    public void setLogLabel (String label) {
        
        lblTransactionLog.setText(label + kiosk.getKioskID());
        
    }
    
    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        account = cmbCards.getSelectedItem().toString();

        lblUser.setText("User: " + account);
        lblUser.setVisible(true);

        if (account.equalsIgnoreCase("admin")) {

            Admin admin = new Admin(kiosk);
            admin.getTransactionLog(this);

        } else {

            accMgmt.getData(account);
            lblBalanceMain.setText("Balance: RM" + accMgmt.getBalance() + "0");
            lblBalance.setText("Balance: RM" + accMgmt.getBalance() + "0");

            Customer customer = new Customer(kiosk);
            customer.viewMainMenu(this);
        }


    }//GEN-LAST:event_btnScanActionPerformed

    public void updateTableTransactions() {
        List<String> transactionList;
        transactionList = orderMgmt.getEntries(kiosk.getKioskID());
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tblTransactions.setAutoCreateRowSorter(true);
        tblTransactions.setModel(table);
        table.addColumn("Order ID");
        table.addColumn("Customer");
        table.addColumn("Item");
        table.addColumn("Cost (RM)");
        for (int i = 0; i < transactionList.size(); i = i + 4) {
            List<String> templist = new ArrayList<>();
            templist.add(transactionList.get(i));
            templist.add(transactionList.get(i + 1));
            templist.add(transactionList.get(i + 2));
            templist.add(transactionList.get(i + 3));
            table.addRow(templist.toArray());
        }
    }

    private void btnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinksActionPerformed
        product = 1;
        switchPanel("pnlDrinks");
    }//GEN-LAST:event_btnDrinksActionPerformed

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
        product = 2;
        switchPanel("pnlFood");
    }//GEN-LAST:event_btnFoodActionPerformed

    private void lblDrinks2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblDrinks2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDrinks2ComponentShown

    private void lblDrinksComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblDrinksComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDrinksComponentShown

    private void lblDrinks1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblDrinks1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDrinks1ComponentShown

    private void lblTotalPriceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblTotalPriceComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTotalPriceComponentShown

    private void lblPaymentComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblPaymentComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPaymentComponentShown

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        kiosk.restart();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        txtpTotal.setText(order);
        lblTotalPrice.setText("Total Price: RM" + cost + "0");
        newBalance = accMgmt.getBalance() - cost;
        lblBalanceAfter.setText("Balance After: RM" + newBalance + "0");

        switchPanel("pnlPayment");
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed

        String selectedFood = String.valueOf(cmbFood.getSelectedItem());

        if (foodMgmt.getAvailability().equalsIgnoreCase("available")) {

            foodOrder = ff.makeFood(selectedFood);
            foodItemOri = foodOrder.getName();
            foodItem = foodItemOri;
            foodOrderBackup = foodOrder;
            getFoodCost(foodOrder);

            System.out.println(foodOrder.getName());
            btnNext1.setEnabled(true);

            if (selectedFood.equals("Tuna Sandwich")) {
                tbtnToastBread.setEnabled(true);
                chkLettuce.setEnabled(true);
                chkOnions.setEnabled(true);
                chkCheese.setEnabled(true);
                chkBBQ.setEnabled(true);
                chkChili.setEnabled(true);
                chkKetchup.setEnabled(true);
                chkMustard.setEnabled(true);
            } else {
                tbtnToastBread.setEnabled(false);
                chkLettuce.setEnabled(false);
                chkLettuce.setSelected(false);
                chkOnions.setEnabled(false);
                chkOnions.setSelected(false);
                chkCheese.setEnabled(false);
                chkCheese.setSelected(false);
                chkBBQ.setEnabled(false);
                chkBBQ.setSelected(false);
                chkChili.setEnabled(false);
                chkChili.setSelected(false);
                chkKetchup.setEnabled(false);
                chkKetchup.setSelected(false);
                chkMustard.setEnabled(false);
                chkMustard.setSelected(false);
            }

        } else {

            int option = JOptionPane.showConfirmDialog(null, "Sorry! Please select a different item.", "Item Unavailable", JOptionPane.DEFAULT_OPTION);

        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void chkOnionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOnionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOnionsActionPerformed

    private void lblSaucesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblSaucesComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaucesComponentShown

    private void lblIngredientsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblIngredientsComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIngredientsComponentShown

    private void lblFood2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblFood2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFood2ComponentShown

    private void cmbFoodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFoodItemStateChanged
        String selectedFood = String.valueOf(cmbFood.getSelectedItem());
        System.out.println(selectedFood);

        txtpSelected.setText(selectedFood);
        foodMgmt.getData(selectedFood);
        txtpAvailability.setText(foodMgmt.getAvailability());
        txtpCost.setText(String.valueOf(foodMgmt.getCost()));

    }//GEN-LAST:event_cmbFoodItemStateChanged

    private void lblFoodComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblFoodComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFoodComponentShown

    private void getFoodCost(Food foodOrder) {

        cost = kiosk.requestFood(foodOrder);
        foodOrderBackup = foodOrder;
        totalCost = "RM" + String.valueOf(cost) + "0";
        setFood();
    }

    private void setFood() {
        order = toasted + foodItem + " - " + totalCost;
        System.out.println(order);
        txtpFood.setText(order);

    }

    // Wraps extra ingredients around the sandwich 
    private void btnAddIngredientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIngredientsActionPerformed
        foodOrder = foodOrderBackup;

        if (chkLettuce.isSelected()) {
            foodOrder = new Lettuce(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkOnions.isSelected()) {
            foodOrder = new Onions(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkCheese.isSelected()) {
            foodOrder = new Cheese(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkBBQ.isSelected()) {
            foodOrder = new BBQSauce(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkChili.isSelected()) {
            foodOrder = new ChiliSauce(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkKetchup.isSelected()) {
            foodOrder = new Ketchup(foodOrder);
            foodItem = foodOrder.getName();
        }

        if (chkMustard.isSelected()) {
            foodOrder = new Mustard(foodOrder);
            foodItem = foodOrder.getName();
        }

        setFood();

    }//GEN-LAST:event_btnAddIngredientsActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed

        txtpTotal.setText(order);
        lblTotalPrice.setText("Total Price: RM" + cost + "0");
        newBalance = accMgmt.getBalance() - cost;
        lblBalanceAfter.setText("Balance After: RM" + newBalance + "0");

        switchPanel("pnlPayment");
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed

        size = "(Medium) ";
        getDrinkCost("M");
        btnNext.setEnabled(true);

    }//GEN-LAST:event_btnMediumActionPerformed

    private String getDrinkAvailability(String drink) {

        String availability;
        drinkMgmt.getData(drink);
        availability = drinkMgmt.getAvailability();

        return availability;

    }

    private void btnMiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiloActionPerformed

        if (getDrinkAvailability("Milo").equalsIgnoreCase("available")) {

            drinkOrder = df.makeDrink("m");
            drinkItem = drinkOrder.getName();
            drinkItemOri = drinkItem;

            btnSmall.setEnabled(true);
            btnMedium.setEnabled(true);
            btnLarge.setEnabled(true);
            btnAddOn.setEnabled(true);

        } else {
            int option = JOptionPane.showConfirmDialog(null, "Sorry! Please select a different item.", "Item Unavailable", JOptionPane.DEFAULT_OPTION);
        }

    }//GEN-LAST:event_btnMiloActionPerformed

    private void btnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeaActionPerformed

        if (getDrinkAvailability("Tea").equalsIgnoreCase("available")) {

            drinkOrder = df.makeDrink("t");
            drinkItem = drinkOrder.getName();
            drinkItemOri = drinkItem;

            btnSmall.setEnabled(true);
            btnMedium.setEnabled(true);
            btnLarge.setEnabled(true);
            btnAddOn.setEnabled(true);

        } else {
            int option = JOptionPane.showConfirmDialog(null, "Sorry! Please select a different item.", "Item Unavailable", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnTeaActionPerformed

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed

        if (getDrinkAvailability("Coffee").equalsIgnoreCase("available")) {

            drinkOrder = df.makeDrink("c");
            drinkItem = drinkOrder.getName();
            drinkItemOri = drinkItem;

            btnSmall.setEnabled(true);
            btnMedium.setEnabled(true);
            btnLarge.setEnabled(true);
            btnAddOn.setEnabled(true);

        } else {
            int option = JOptionPane.showConfirmDialog(null, "Sorry! Please select a different item.", "Item Unavailable", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void getDrinkCost(String size) {

        cost = kiosk.requestDrink(drinkOrder, size);
        drinkOrderBackup = drinkOrder;
        totalCost = "RM" + String.valueOf(cost) + "0";
        setDrinks();
    }

    private void setDrinks() {

        order = size + this.drinkItem + " - " + totalCost;
        System.out.println(order);
        txtpDrinks.setText(order);

    }

    private void btnSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallActionPerformed

        size = "(Small) ";
        getDrinkCost("S");
        btnNext.setEnabled(true);

    }//GEN-LAST:event_btnSmallActionPerformed

    private void btnLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLargeActionPerformed

        size = "(Large) ";
        getDrinkCost("L");
        btnNext.setEnabled(true);

    }//GEN-LAST:event_btnLargeActionPerformed

    private void cmbMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMilkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMilkActionPerformed

    private void cmbMilkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMilkItemStateChanged


    }//GEN-LAST:event_cmbMilkItemStateChanged

    private void btnAddOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOnActionPerformed
        drinkOrder = drinkOrderBackup;

        // Adding Milk
        String amountMilk = String.valueOf(cmbMilk.getSelectedItem());

        switch (drinkItemOri) {
            case "Milo":
                drinkOrder = new Milk(drinkOrder, amountMilk);
                drinkItem = drinkOrder.getName();
                System.out.println(drinkItem);
                break;
            case "Tea":
                drinkOrder = new Milk(drinkOrder, amountMilk);
                drinkItem = drinkOrder.getName();
                break;
            case "Coffee":
                drinkOrder = new Milk(drinkOrder, amountMilk);
                drinkItem = drinkOrder.getName();
                break;
        }

        // Adding Sugar
        String amountSugar = String.valueOf(cmbSugar.getSelectedItem());

        switch (drinkItemOri) {
            case "Milo":
                drinkOrder = new Sugar(drinkOrder, amountSugar);
                drinkItem = drinkOrder.getName();
                System.out.println(drinkItem);
                break;
            case "Tea":
                drinkOrder = new Sugar(drinkOrder, amountSugar);
                drinkItem = drinkOrder.getName();
                break;
            case "Coffee":
                drinkOrder = new Sugar(drinkOrder, amountSugar);
                drinkItem = drinkOrder.getName();
                break;
        }

        // Adding Ice
        String amountIce = String.valueOf(cmbIce.getSelectedItem());

        switch (drinkItemOri) {
            case "Milo":
                drinkOrder = new Ice(drinkOrder, amountIce);
                drinkItem = drinkOrder.getName();
                System.out.println(drinkItem);
                break;
            case "Tea":
                drinkOrder = new Ice(drinkOrder, amountIce);
                drinkItem = drinkOrder.getName();
                break;
            case "Coffee":
                drinkOrder = new Ice(drinkOrder, amountIce);
                drinkItem = drinkOrder.getName();
                break;
        }

        // Adding Chocolate Sprinkles
        String amountChoc = String.valueOf(cmbChoc.getSelectedItem());

        switch (drinkItemOri) {
            case "Milo":
                drinkOrder = new ChocolateSprinkles(drinkOrder, amountChoc);
                drinkItem = drinkOrder.getName();
                System.out.println(drinkItem);
                break;
            case "Tea":
                drinkOrder = new ChocolateSprinkles(drinkOrder, amountChoc);
                drinkItem = drinkOrder.getName();
                break;
            case "Coffee":
                drinkOrder = new ChocolateSprinkles(drinkOrder, amountChoc);
                drinkItem = drinkOrder.getName();
                break;
        }

        setDrinks();

    }//GEN-LAST:event_btnAddOnActionPerformed

    private void lblBalanceComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBalanceComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBalanceComponentShown

    private void lblBalanceAfterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBalanceAfterComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBalanceAfterComponentShown

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        int option;
        
        if (newBalance <= 0) {
            option = JOptionPane.showConfirmDialog(null, "Insufficient balance. Please top up your account and try again. Logging you out.", "Transaction Failed", JOptionPane.DEFAULT_OPTION);
        } else {
            
            option = JOptionPane.showConfirmDialog(null, "New balance: RM" + newBalance + "0\nPlease collect your item at the snack booth on Level 3.", "Payment successful!", JOptionPane.DEFAULT_OPTION);

            accMgmt.updateBalance(account, newBalance);

            orderMgmt.updateOrderCount();
            int orderID = orderMgmt.getOrderCount();

            if (product == 1) {
                drinkItem = size + drinkItem;

                orderMgmt.addOrder(orderID, account, drinkItem, cost);
            } else {

                foodItem = toasted + foodItem;
                orderMgmt.addOrder(orderID, account, foodItem, cost);

            }

            SnackBooth.getInstance().getMenu().updateTableMain();
            
        }

        if (option == JOptionPane.OK_OPTION) {
            System.out.println("OK!");
            kiosk.restart();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tbtnToastBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnToastBreadActionPerformed
        if (tbtnToastBread.isSelected() == true) {
            toasted = "(Toasted Bread) ";
        } else {
            toasted = "";
        }

        setFood();
    }//GEN-LAST:event_tbtnToastBreadActionPerformed

    private void cmbFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFoodActionPerformed

    private void lblBalanceMainComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblBalanceMainComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBalanceMainComponentShown

    private void lblTransactionLogComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblTransactionLogComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTransactionLogComponentShown

    private void lblDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDoneActionPerformed
        kiosk.restart();
    }//GEN-LAST:event_lblDoneActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        kiosk.viewMoreDetails(tblTransactions);

    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KioskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KioskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KioskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KioskGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KioskGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIngredients;
    private javax.swing.JButton btnAddOn;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnFood;
    private javax.swing.JButton btnLarge;
    private javax.swing.JButton btnMedium;
    private javax.swing.JButton btnMilo;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnScan;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSmall;
    private javax.swing.JButton btnTea;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkBBQ;
    private javax.swing.JCheckBox chkCheese;
    private javax.swing.JCheckBox chkChili;
    private javax.swing.JCheckBox chkKetchup;
    private javax.swing.JCheckBox chkLettuce;
    private javax.swing.JCheckBox chkMustard;
    private javax.swing.JCheckBox chkOnions;
    private javax.swing.JComboBox<String> cmbCards;
    private javax.swing.JComboBox<String> cmbChoc;
    private javax.swing.JComboBox<String> cmbFood;
    private javax.swing.JComboBox<String> cmbIce;
    private javax.swing.JComboBox<String> cmbMilk;
    private javax.swing.JComboBox<String> cmbSugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAddOn;
    private javax.swing.JLabel lblAddOn1;
    private javax.swing.JLabel lblAddOn2;
    private javax.swing.JLabel lblAddOn3;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBalanceAfter;
    private javax.swing.JLabel lblBalanceMain;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JButton lblDone;
    private javax.swing.JLabel lblDrinks;
    private javax.swing.JLabel lblDrinks1;
    private javax.swing.JLabel lblDrinks2;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblFood2;
    private javax.swing.JLabel lblIngredients;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblNext1;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSauces;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblTransactionLog;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlDrinks;
    private javax.swing.JPanel pnlFood;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JScrollPane scrlDrinks;
    private javax.swing.JScrollPane scrlFood;
    private javax.swing.JScrollPane scrlPrice;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JToggleButton tbtnToastBread;
    private javax.swing.JTextPane txtpAvailability;
    private javax.swing.JTextPane txtpCost;
    private javax.swing.JTextPane txtpDrinks;
    private javax.swing.JTextPane txtpFood;
    private javax.swing.JTextPane txtpSelected;
    private javax.swing.JTextArea txtpTotal;
    // End of variables declaration//GEN-END:variables
}
