/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snackbooth.GUI;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import snackbooth.Database.DrinkManagement;
import snackbooth.Database.FoodManagement;
import snackbooth.Database.OrderManagement;
import snackbooth.Kiosk;

/**
 *
 * @author PC
 */
public class SnackBoothGUI extends javax.swing.JFrame {

    /**
     * Creates new form SnackBoothGUI
     */
    Kiosk k1;
    Kiosk k2;
    Kiosk k3;
    Kiosk k4;
    Kiosk k5;

    OrderManagement orderMgmt = new OrderManagement(null);
    DrinkManagement drinkMgmt = DrinkManagement.getInstance();
    FoodManagement foodMgmt = FoodManagement.getInstance();

    public SnackBoothGUI() {
        initComponents();

        updateTableMain();
        updateTableDrinks();
        updateTableFood();
        k1 = new Kiosk(1);
        k2 = new Kiosk(2);
        k3 = new Kiosk(3);
        k4 = new Kiosk(4);
        k5 = new Kiosk(5);

    }

    public void updateTableMain() {
        List<String> listeditem;
        listeditem = orderMgmt.getEntries();
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tblMain.setAutoCreateRowSorter(true);
        tblMain.setModel(table);
        table.addColumn("Order ID");
        table.addColumn("Customer");
        table.addColumn("Item");
        table.addColumn("Cost (RM)");
        for (int i = 0; i < listeditem.size(); i = i + 4) {
            List<String> templist = new ArrayList<>();
            templist.add(listeditem.get(i));
            templist.add(listeditem.get(i + 1));
            templist.add(listeditem.get(i + 2));
            templist.add(listeditem.get(i + 3));
            table.addRow(templist.toArray());
        }
    }

    public void updateTableDrinks() {
        List<String> listeditem;
        listeditem = drinkMgmt.getEntries();
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return true;
            }
        };
        tblDrinks.setAutoCreateRowSorter(true);
        tblDrinks.setModel(table);
        table.addColumn("Name");
        table.addColumn("Small (RM)");
        table.addColumn("Medium (RM)");
        table.addColumn("Large (RM)");
        table.addColumn("Available/Unavailable");

        for (int i = 0; i < listeditem.size(); i = i + 5) {
            List<String> templist = new ArrayList<>();
            templist.add(listeditem.get(i));
            templist.add(listeditem.get(i + 1));
            templist.add(listeditem.get(i + 2));
            templist.add(listeditem.get(i + 3));
            templist.add(listeditem.get(i + 4));
            table.addRow(templist.toArray());
        }
    }

    public void updateTableFood() {
        List<String> listeditem;
        listeditem = foodMgmt.getEntries();
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return true;
            }
        };
        tblFood.setAutoCreateRowSorter(true);
        tblFood.setModel(table);
        table.addColumn("Name");
        table.addColumn("Cost (RM)");
        table.addColumn("Available/Unavailable");

        for (int i = 0; i < listeditem.size(); i = i + 3) {
            List<String> templist = new ArrayList<>();
            templist.add(listeditem.get(i));
            templist.add(listeditem.get(i + 1));
            templist.add(listeditem.get(i + 2));
            table.addRow(templist.toArray());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMainPage = new javax.swing.JPanel();
        lblMainPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        btnMainPageFulfil = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        pnlAdmin = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblAdmin2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrinks = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFood = new javax.swing.JTable();
        btnUpdateDrinks = new javax.swing.JButton();
        btnUpdateFood = new javax.swing.JButton();
        pnlKiosks = new javax.swing.JPanel();
        lblKiosks = new javax.swing.JLabel();
        lblKiosk1 = new javax.swing.JLabel();
        lblKiosk2 = new javax.swing.JLabel();
        lblKiosk3 = new javax.swing.JLabel();
        btnOff1 = new javax.swing.JButton();
        btnOn1 = new javax.swing.JButton();
        btnOff2 = new javax.swing.JButton();
        btnOn2 = new javax.swing.JButton();
        btnOff3 = new javax.swing.JButton();
        btnOn3 = new javax.swing.JButton();
        lblKiosk4 = new javax.swing.JLabel();
        btnOn4 = new javax.swing.JButton();
        btnOff4 = new javax.swing.JButton();
        lblKiosk5 = new javax.swing.JLabel();
        btnOn5 = new javax.swing.JButton();
        btnOff5 = new javax.swing.JButton();
        lblKiosk6 = new javax.swing.JLabel();
        btnOn6 = new javax.swing.JButton();
        btnOff6 = new javax.swing.JButton();
        lblKiosk7 = new javax.swing.JLabel();
        btnOn7 = new javax.swing.JButton();
        btnOff7 = new javax.swing.JButton();
        btnOff8 = new javax.swing.JButton();
        btnOn8 = new javax.swing.JButton();
        lblKiosk8 = new javax.swing.JLabel();
        btnOn9 = new javax.swing.JButton();
        lblKiosk9 = new javax.swing.JLabel();
        btnOff9 = new javax.swing.JButton();
        lblKiosk10 = new javax.swing.JLabel();
        btnOn10 = new javax.swing.JButton();
        btnOff10 = new javax.swing.JButton();
        MainTitle = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        btnPanelTwo = new javax.swing.JButton();
        btnPanelThree = new javax.swing.JButton();
        btnPanelOne = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snack Booth");

        pnlMain.setLayout(new java.awt.CardLayout());

        lblMainPage.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        lblMainPage.setText("Main Page");

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order #", "Customer", "Item", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMain.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblMainComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);

        btnMainPageFulfil.setText("Fulfil");
        btnMainPageFulfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainPageFulfilActionPerformed(evt);
            }
        });

        btnView.setText("View More");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainPageLayout = new javax.swing.GroupLayout(pnlMainPage);
        pnlMainPage.setLayout(pnlMainPageLayout);
        pnlMainPageLayout.setHorizontalGroup(
            pnlMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainPageLayout.createSequentialGroup()
                        .addComponent(lblMainPage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addGroup(pnlMainPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMainPageFulfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlMainPageLayout.setVerticalGroup(
            pnlMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainPage)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMainPageFulfil)
                    .addComponent(btnView))
                .addContainerGap())
        );

        pnlMain.add(pnlMainPage, "pnlMainPage");

        lblAdmin.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        lblAdmin.setText("Product Management");

        lblAdmin2.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblAdmin2.setText("Price and Availability Management (Note: Press the enter key after keying in new values)");

        tblDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drink", "Stock", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDrinks);

        tblFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food", "Stock", "Price"
            }
        ));
        jScrollPane3.setViewportView(tblFood);

        btnUpdateDrinks.setText("Update");
        btnUpdateDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDrinksActionPerformed(evt);
            }
        });

        btnUpdateFood.setText("Update");
        btnUpdateFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdmin)
                            .addComponent(lblAdmin2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateFood, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateDrinks, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdmin)
                .addGap(18, 18, 18)
                .addComponent(lblAdmin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateDrinks)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateFood)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlMain.add(pnlAdmin, "pnlAdmin");

        lblKiosks.setFont(new java.awt.Font("Roboto Cn", 1, 18)); // NOI18N
        lblKiosks.setText("Kiosk Management (Only Kiosks 1-5 are functional for now)");

        lblKiosk1.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk1.setText("Kiosk 1");

        lblKiosk2.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk2.setText("Kiosk 2");

        lblKiosk3.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk3.setText("Kiosk 3");

        btnOff1.setText("Off");
        btnOff1.setEnabled(false);
        btnOff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff1ActionPerformed(evt);
            }
        });

        btnOn1.setText("On");
        btnOn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn1ActionPerformed(evt);
            }
        });

        btnOff2.setText("Off");
        btnOff2.setEnabled(false);
        btnOff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff2ActionPerformed(evt);
            }
        });

        btnOn2.setText("On");
        btnOn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn2ActionPerformed(evt);
            }
        });

        btnOff3.setText("Off");
        btnOff3.setEnabled(false);
        btnOff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff3ActionPerformed(evt);
            }
        });

        btnOn3.setText("On");
        btnOn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn3ActionPerformed(evt);
            }
        });

        lblKiosk4.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk4.setText("Kiosk 4");

        btnOn4.setText("On");
        btnOn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn4ActionPerformed(evt);
            }
        });

        btnOff4.setText("Off");
        btnOff4.setEnabled(false);
        btnOff4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff4ActionPerformed(evt);
            }
        });

        lblKiosk5.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk5.setText("Kiosk 5");

        btnOn5.setText("On");
        btnOn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn5ActionPerformed(evt);
            }
        });

        btnOff5.setText("Off");
        btnOff5.setEnabled(false);
        btnOff5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff5ActionPerformed(evt);
            }
        });

        lblKiosk6.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk6.setText("Kiosk 6");

        btnOn6.setText("On");
        btnOn6.setEnabled(false);
        btnOn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn6ActionPerformed(evt);
            }
        });

        btnOff6.setText("Off");
        btnOff6.setEnabled(false);
        btnOff1.setEnabled(false);
        btnOff6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff6ActionPerformed(evt);
            }
        });

        lblKiosk7.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk7.setText("Kiosk 7");

        btnOn7.setText("On");
        btnOn7.setEnabled(false);
        btnOn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn7ActionPerformed(evt);
            }
        });

        btnOff7.setText("Off");
        btnOff7.setEnabled(false);
        btnOff2.setEnabled(false);
        btnOff7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff7ActionPerformed(evt);
            }
        });

        btnOff8.setText("Off");
        btnOff8.setEnabled(false);
        btnOff3.setEnabled(false);
        btnOff8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff8ActionPerformed(evt);
            }
        });

        btnOn8.setText("On");
        btnOn8.setEnabled(false);
        btnOn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn8ActionPerformed(evt);
            }
        });

        lblKiosk8.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk8.setText("Kiosk 8");

        btnOn9.setText("On");
        btnOn9.setEnabled(false);
        btnOn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn9ActionPerformed(evt);
            }
        });

        lblKiosk9.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk9.setText("Kiosk 9");

        btnOff9.setText("Off");
        btnOff9.setEnabled(false);
        btnOff4.setEnabled(false);
        btnOff9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff9ActionPerformed(evt);
            }
        });

        lblKiosk10.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lblKiosk10.setText("Kiosk 10");

        btnOn10.setText("On");
        btnOn10.setEnabled(false);
        btnOn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOn10ActionPerformed(evt);
            }
        });

        btnOff10.setText("Off");
        btnOff10.setEnabled(false);
        btnOff5.setEnabled(false);
        btnOff10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOff10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKiosksLayout = new javax.swing.GroupLayout(pnlKiosks);
        pnlKiosks.setLayout(pnlKiosksLayout);
        pnlKiosksLayout.setHorizontalGroup(
            pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKiosksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKiosks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlKiosksLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKiosk1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKiosk2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKiosk3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKiosk4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKiosk5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKiosk7)
                    .addComponent(lblKiosk6)
                    .addComponent(lblKiosk8)
                    .addComponent(lblKiosk9)
                    .addComponent(lblKiosk10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addComponent(btnOn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOff6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        pnlKiosksLayout.setVerticalGroup(
            pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKiosksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKiosks)
                .addGap(12, 12, 12)
                .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn6)
                            .addComponent(btnOff6)
                            .addComponent(lblKiosk6))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn7)
                            .addComponent(btnOff7)
                            .addComponent(lblKiosk7))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn8)
                            .addComponent(btnOff8)
                            .addComponent(lblKiosk8))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn9)
                            .addComponent(btnOff9)
                            .addComponent(lblKiosk9))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn10)
                            .addComponent(btnOff10)
                            .addComponent(lblKiosk10)))
                    .addGroup(pnlKiosksLayout.createSequentialGroup()
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn1)
                            .addComponent(btnOff1)
                            .addComponent(lblKiosk1))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn2)
                            .addComponent(btnOff2)
                            .addComponent(lblKiosk2))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn3)
                            .addComponent(btnOff3)
                            .addComponent(lblKiosk3))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn4)
                            .addComponent(btnOff4)
                            .addComponent(lblKiosk4))
                        .addGap(33, 33, 33)
                        .addGroup(pnlKiosksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOn5)
                            .addComponent(btnOff5)
                            .addComponent(lblKiosk5))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlMain.add(pnlKiosks, "pnlKiosks");

        MainTitle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        MainTitle.setText("Main");
        pnlMain.add(MainTitle, "card3");

        Title.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Title.setText("Snack Booth");

        btnPanelTwo.setText("Admin");
        btnPanelTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelTwoActionPerformed(evt);
            }
        });

        btnPanelThree.setText("Kiosks");
        btnPanelThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelThreeActionPerformed(evt);
            }
        });

        btnPanelOne.setText("Main");
        btnPanelOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelOneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPanelOne, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPanelThree, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPanelThree)
                        .addComponent(btnPanelTwo)
                        .addComponent(btnPanelOne))
                    .addComponent(Title))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelOneActionPerformed
        CardLayout card = (CardLayout) pnlMain.getLayout();
        card.show(pnlMain, "pnlMainPage");
    }//GEN-LAST:event_btnPanelOneActionPerformed

    private void btnPanelTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelTwoActionPerformed
        CardLayout card = (CardLayout) pnlMain.getLayout();
        card.show(pnlMain, "pnlAdmin");
    }//GEN-LAST:event_btnPanelTwoActionPerformed

    private void btnPanelThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelThreeActionPerformed
        CardLayout card = (CardLayout) pnlMain.getLayout();
        card.show(pnlMain, "pnlKiosks");
    }//GEN-LAST:event_btnPanelThreeActionPerformed

    private void btnMainPageFulfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainPageFulfilActionPerformed
        orderMgmt.fulfilOrder(tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString());
        JOptionPane.showConfirmDialog(null, "Order successfully fulfilled!", "Order Fulfilled", JOptionPane.DEFAULT_OPTION);
        updateTableMain();
    }//GEN-LAST:event_btnMainPageFulfilActionPerformed

    private void btnOff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff1ActionPerformed
        btnOn1.setEnabled(true);
        btnOff1.setEnabled(false);
        k1.change();
    }//GEN-LAST:event_btnOff1ActionPerformed

    private void btnOn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn1ActionPerformed
        btnOff1.setEnabled(true);
        btnOn1.setEnabled(false);

        k1.change();
    }//GEN-LAST:event_btnOn1ActionPerformed

    private void btnOff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff2ActionPerformed
        btnOn2.setEnabled(true);
        btnOff2.setEnabled(false);

        k2.change();
    }//GEN-LAST:event_btnOff2ActionPerformed

    private void btnOn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn2ActionPerformed
        btnOff2.setEnabled(true);
        btnOn2.setEnabled(false);

        k2.change();
    }//GEN-LAST:event_btnOn2ActionPerformed

    private void btnOff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff3ActionPerformed
        btnOn3.setEnabled(true);
        btnOff3.setEnabled(false);

        k3.change();
    }//GEN-LAST:event_btnOff3ActionPerformed

    private void btnOn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn3ActionPerformed
        btnOff3.setEnabled(true);
        btnOn3.setEnabled(false);

        k3.change();
    }//GEN-LAST:event_btnOn3ActionPerformed

    private void btnOn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn4ActionPerformed
        btnOff4.setEnabled(true);
        btnOn4.setEnabled(false);

        k4.change();
    }//GEN-LAST:event_btnOn4ActionPerformed

    private void btnOff4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff4ActionPerformed
        btnOn4.setEnabled(true);
        btnOff4.setEnabled(false);

        k4.change();
    }//GEN-LAST:event_btnOff4ActionPerformed

    private void btnOn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn5ActionPerformed
        btnOff5.setEnabled(true);
        btnOn5.setEnabled(false);

        k5.change();
    }//GEN-LAST:event_btnOn5ActionPerformed

    private void btnOff5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff5ActionPerformed
        btnOn5.setEnabled(true);
        btnOff5.setEnabled(false);

        k5.change();
    }//GEN-LAST:event_btnOff5ActionPerformed

    private void tblMainComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblMainComponentShown

    }//GEN-LAST:event_tblMainComponentShown

    // Writes drink modifications into the text file 
    public void writeTableDrinks() {
        List<String> newItems = drinkMgmt.getEntries();
        DefaultTableModel table = (DefaultTableModel) tblDrinks.getModel(); 

        int rows = table.getRowCount(), cols = table.getColumnCount();

        newItems.removeAll(newItems);

        for (int i = 0; i < rows; i++) {

            newItems.add(String.valueOf(table.getValueAt(i, 0)));
            newItems.add(String.valueOf(table.getValueAt(i, 1)));
            newItems.add(String.valueOf(table.getValueAt(i, 2)));
            newItems.add(String.valueOf(table.getValueAt(i, 3)));
            newItems.add(String.valueOf(table.getValueAt(i, 4)));
        }

        drinkMgmt.updateDrinks(newItems);
    }

    public void writeTableFood() {
        List<String> newItems = foodMgmt.getEntries();
        DefaultTableModel table = (DefaultTableModel) tblFood.getModel();

        int rows = table.getRowCount(), cols = table.getColumnCount();

        newItems.removeAll(newItems);

        for (int i = 0; i < rows; i++) {

            newItems.add(String.valueOf(table.getValueAt(i, 0)));
            newItems.add(String.valueOf(table.getValueAt(i, 1)));
            newItems.add(String.valueOf(table.getValueAt(i, 2)));
        }

        foodMgmt.updateFood(newItems);
    }

    private void btnUpdateDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDrinksActionPerformed

        writeTableDrinks();

        JOptionPane.showConfirmDialog(null, "Drink information successfully updated!", "Update Successful", JOptionPane.DEFAULT_OPTION);

    }//GEN-LAST:event_btnUpdateDrinksActionPerformed

    private void btnUpdateFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFoodActionPerformed

        writeTableFood();

        JOptionPane.showConfirmDialog(null, "Food information successfully updated!", "Update Successful", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_btnUpdateFoodActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
            k1.viewMoreDetails(tblMain);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnOn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOn6ActionPerformed

    private void btnOff6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOff6ActionPerformed

    private void btnOn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOn7ActionPerformed

    private void btnOff7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOff7ActionPerformed

    private void btnOff8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOff8ActionPerformed

    private void btnOn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOn8ActionPerformed

    private void btnOn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOn9ActionPerformed

    private void btnOff9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOff9ActionPerformed

    private void btnOn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOn10ActionPerformed

    private void btnOff10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOff10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOff10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnackBoothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnackBoothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnackBoothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnackBoothGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnackBoothGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnMainPageFulfil;
    private javax.swing.JButton btnOff1;
    private javax.swing.JButton btnOff10;
    private javax.swing.JButton btnOff2;
    private javax.swing.JButton btnOff3;
    private javax.swing.JButton btnOff4;
    private javax.swing.JButton btnOff5;
    private javax.swing.JButton btnOff6;
    private javax.swing.JButton btnOff7;
    private javax.swing.JButton btnOff8;
    private javax.swing.JButton btnOff9;
    private javax.swing.JButton btnOn1;
    private javax.swing.JButton btnOn10;
    private javax.swing.JButton btnOn2;
    private javax.swing.JButton btnOn3;
    private javax.swing.JButton btnOn4;
    private javax.swing.JButton btnOn5;
    private javax.swing.JButton btnOn6;
    private javax.swing.JButton btnOn7;
    private javax.swing.JButton btnOn8;
    private javax.swing.JButton btnOn9;
    private javax.swing.JButton btnPanelOne;
    private javax.swing.JButton btnPanelThree;
    private javax.swing.JButton btnPanelTwo;
    private javax.swing.JButton btnUpdateDrinks;
    private javax.swing.JButton btnUpdateFood;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdmin2;
    private javax.swing.JLabel lblKiosk1;
    private javax.swing.JLabel lblKiosk10;
    private javax.swing.JLabel lblKiosk2;
    private javax.swing.JLabel lblKiosk3;
    private javax.swing.JLabel lblKiosk4;
    private javax.swing.JLabel lblKiosk5;
    private javax.swing.JLabel lblKiosk6;
    private javax.swing.JLabel lblKiosk7;
    private javax.swing.JLabel lblKiosk8;
    private javax.swing.JLabel lblKiosk9;
    private javax.swing.JLabel lblKiosks;
    private javax.swing.JLabel lblMainPage;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlKiosks;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainPage;
    private javax.swing.JTable tblDrinks;
    private javax.swing.JTable tblFood;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
